trigger: none

pool:
  name: 'Default'
  demands:
    - agent.name -equals instance-20250115-185328

variables:
  GCP_SERVICE_CONNECTION: 'mygcpconnection'
  Working_Directory: '$(System.DefaultWorkingDirectory)/HelmCharts'

steps: 

- script: |
    gcloud container clusters get-credentials $(CLUSTER_NAME) --region $(REGION) --project $(PROJECT)
  workingDirectory: $(Working_Directory)
  displayName: 'Connection to GKE'

- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'


- script: |
    helm upgrade --install medfast-frontend ./HelmCharts/frontapp \
      --set image.tag=${BUILD_ID} \
      --namespace default \
      --wait \
      --force
  displayName: 'Deploy with Helm'