trigger: none

resources:
- repo: self

pool:
    name: 'Default'
    demands:
        - agent.name -equals instance-20250115-185328

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'romanbeggar/frontend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile' 
    tags: |
      $(Build.BuildId)
  displayName: 'Build and push Docker image'

