trigger: none

pool:
  name: 'Default'
  demands:
    - agent.name -equals instance-20250115-185328

variables:
  GCP_SERVICE_CONNECTION: 'mygcpconnection'
  Working_Directory: '$(System.DefaultWorkingDirectory)/HelmCharts'

steps: 

- script: |
    gcloud container clusters get-credentials $(CLUSTER_NAME) --region $(REGION) --project $(PROJECT)
  workingDirectory: $(Working_Directory)
  displayName: 'Connection to GKE'

- script: |
    terraform init -input=false
  workingDirectory: '$(Working_Directory)'
  displayName: 'Terraform Init for frontend'

- script: |
    terraform apply -auto-approve -var="image_tag=${TAG}"
  workingDirectory: '$(Working_Directory)'
  displayName: 'Deploy frontend application'