# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool:
    name: 'Default'
    demands:
        - agent.name -equals instance-20241203-145320


variables:
  API_HOST: "http://medfast-backend:8080"

steps:

- script: |
    echo "API_HOST=$(API_HOST)" > $(Build.SourcesDirectory)/.env
  displayName: 'Create .env file with API_HOST'

- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'romanbeggar/frontend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: $(Build.SourcesDirectory)
    additionalOptions: '--env-file $(Build.SourcesDirectory)/.env'  # передаем .env файл при билде Docker образа
    tags: |
      $(Build.BuildId)
  displayName: 'Build and push Docker image'

